<Wid_Alfa>:
    canvas:
        Color:
            rgb:1,1,1
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: 1,0,0,.5
        Rectangle:
            pos: 320,50
            size: 150,150
        Color:
            hsv: .3,.7,.9
            a: .7
        Ellipse:
            pos: 100,100
            size: 200,200
            angle_start: 30
            angle_end: 90