<WidAlfa>:
    canvas:
        Color:
            rgb: 0,0,0
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgb: 1,1,1
        Rectangle:
            pos: self.pos
            size: [200,250]
            source: 'atlas://media/ejemplo.atlas/paso1'
        Rectangle:
            pos: [200,0]
            #size: [400,500]
            size: [27,169]
            source: self.my_source