media = "atlas://styles/src/colors.atlas/"

transparency = media+"transparency"
shadow20 = media+"shadow20"
shadow40 = media+"shadow40"
shadow60 = media+"shadow60"
shadow80 = media+"shadow80"
red  = media+"red"
yellow = media+"yellow"
green = media+"green"
turquoise = media+"turquoise"
black = media+"black"
pink = media+"pink"
orange = media+"orange"
blue = media+"blue"
purble = media+"purble"
withe = media+"withe"
colors = media+"colors"
